export const data = {
    Product:[
        {
        package:'Budget Package - 1,650/sq.ft',
        list0:'Design & Drawing',
        list00:"Basic Elevation",
        list000:"Structural Design",
        list1:'Structure',
        list11:"Steel - Sunvik or Equivalent",
        list111:'Aggregates - 20mm&40mm',
        list1111:'Blocks - Standard Soild Concrete blocks. 6inch 4inch',
        list11111:'Cement - Dalmia , Coromandel or Zuari or equivalent Portland Pozzolona Cement',
        list111111:'RCC Design Mix - As Per the Structural designer recommentation',
        list1111111:'Celing height - 10 feet(Finished Floor level to Finished Floor Level)',
        list2:'Kitchen',
        list22:'Ceramic Wall Tiles, 2 feet above Kitchen slab - upto Rs.40per sqft',
        list222:'Main sink Faucet - upto Rs.1300',
        list2222:'Any Other Faucet & Accessories - ISI Marked',
        list22222:'Kitchen Sink - Stainless Steel Single Sink Worth Rs.3000',
        list3:'Bathroom',
        list33:'Bathroom Ceramic Wall Tiles with 7 feet height - Upto Rs.40 per Sqft',
        list333:'Sanitary ware &amp; CP Fittings - Upto Rs.30000 per 1000sqft of construction.',
        list3333:'CPVC Pipe - Astral or equivalent',
        list33333:'Bathroom doors - Waterproof flush doors',
        list4:'Door & Windows',
        list44:'Main Door - Flush Door With Veneer. Sal wood frame of 5 inch by 3 inch, worth Rs.13000 including fixtures',
        list444:'Internal Doors - Membrane doors / Flush Door with Laminates upto Rs.8000 including fixtures. Door Frames of Sal Wood 4inch by 2.5 inch',
        list4444:'Windows - Aluminium Windows with glass shutters and mesh shutters(3 track with 1 mesh)',
        list5:'Painting',
        list55:'Interior Painting - JK Putty + Tractor Emulsion or equivalent',
        list555:'Exterior Painting - Asian Primer + Ace Exterior Emulsion Paint or equivalent',
        list6:'Flooring',
        list66:'Living and Dining Flooring - Tiles of value upto Rs.50 per sqft',
        list666:'Rooms and Kitchen Flooring - Tiles upto Rs.50 per sqftExterior Painting - Asian Primer + Ace Exterior Emulsion Paint or equivalent',
        list6666:'Balcony and Open Areas Flooring - Anti-skid tiles of value upto Rs.40 per sqft',
        list66666:'Staircase Flooring - Sadarahalli Granite of value upto ₹ 70 per sqft',
        list666666:'Parking Tiles - Anti-skid tiles of value upto ₹40 per sqft',
        list7:'Electrical',
        list77:'Wires - Fireproof wires by Finolex',
        list777:'Switches &amp; Sockets - Anchor Roma',
        list8:'Miscellaneous',
        list88:'Overhead Tank - Sintex Double Layered 1000 ltrs',
        list888:'Underground Sump - 4000 litres',
        list8888:'Staircase Railing - MS Railing',
        list9:'Costomisation Costs',

    },
    {
        package:'Budget Package - 1,750/sq.ft',
        list0:'Design & Drawing',
        list00:"Basic Elevation",
        list000:"Structural Design",
        list1:'Structure',
        list11:"Steel - Sunvik or Equivalent",
        list111:'Aggregates - 20mm&40mm',
        list1111:'Blocks - Standard Soild Concrete blocks. 6inch 4inch',
        list11111:'Cement - Dalmia , Coromandel or Zuari or equivalent Portland Pozzolona Cement',
        list111111:'RCC Design Mix - As Per the Structural designer recommentation',
        list1111111:'Celing height - 10 feet(Finished Floor level to Finished Floor Level)',
        list2:'Kitchen',
        list22:'Ceramic Wall Tiles, 2 feet above Kitchen slab - upto Rs.40per sqft',
        list222:'Main sink Faucet - upto Rs.1300',
        list2222:'Any Other Faucet & Accessories - ISI Marked',
        list22222:'Kitchen Sink - Stainless Steel Single Sink Worth Rs.3000',
        list3:'Bathroom',
        list33:'Bathroom Ceramic Wall Tiles with 7 feet height - Upto Rs.40 per Sqft',
        list333:'Sanitary ware &amp; CP Fittings - Upto Rs.30000 per 1000sqft of construction.',
        list3333:'CPVC Pipe - Astral or equivalent',
        list33333:'Bathroom doors - Waterproof flush doors',
        list4:'Door & Windows',
        list44:'Main Door - Flush Door With Veneer. Sal wood frame of 5 inch by 3 inch, worth Rs.13000 including fixtures',
        list444:'Internal Doors - Membrane doors / Flush Door with Laminates upto Rs.8000 including fixtures. Door Frames of Sal Wood 4inch by 2.5 inch',
        list4444:'Windows - Aluminium Windows with glass shutters and mesh shutters(3 track with 1 mesh)',
        list5:'Painting',
        list55:'Interior Painting - JK Putty + Tractor Emulsion or equivalent',
        list555:'Exterior Painting - Asian Primer + Ace Exterior Emulsion Paint or equivalent',
        list6:'Flooring',
        list66:'Living and Dining Flooring - Tiles of value upto Rs.50 per sqft',
        list666:'Rooms and Kitchen Flooring - Tiles upto Rs.50 per sqftExterior Painting - Asian Primer + Ace Exterior Emulsion Paint or equivalent',
        list6666:'Balcony and Open Areas Flooring - Anti-skid tiles of value upto Rs.40 per sqft',
        list66666:'Staircase Flooring - Sadarahalli Granite of value upto ₹ 70 per sqft',
        list666666:'Parking Tiles - Anti-skid tiles of value upto ₹40 per sqft',

        list7:'Electrical',
        list77:'Wires - Fireproof wires by Finolex',
        list777:'Switches &amp; Sockets - Anchor Roma',
        list8:'Miscellaneous',
        list88:'Overhead Tank - Sintex Double Layered 1000 ltrs',
        list888:'Underground Sump - 4000 litres',
        list8888:'Staircase Railing - MS Railing',
        list9:'Costomisation Costs',

    },{
        package:'Budget Package - 1,850/sq.ft',
        list0:'Design & Drawing',
        list00:"Basic Elevation",
        list000:"Structural Design",
        list1:'Structure',
        list11:"Steel - Sunvik or Equivalent",
        list111:'Aggregates - 20mm&40mm',
        list1111:'Blocks - Standard Soild Concrete blocks. 6inch 4inch',
        list11111:'Cement - Dalmia , Coromandel or Zuari or equivalent Portland Pozzolona Cement',
        list111111:'RCC Design Mix - As Per the Structural designer recommentation',
        list1111111:'Celing height - 10 feet(Finished Floor level to Finished Floor Level)',
        list2:'Kitchen',
        list22:'Ceramic Wall Tiles, 2 feet above Kitchen slab - upto Rs.40per sqft',
        list222:'Main sink Faucet - upto Rs.1300',
        list2222:'Any Other Faucet & Accessories - ISI Marked',
        list22222:'Kitchen Sink - Stainless Steel Single Sink Worth Rs.3000',
        list3:'Bathroom',
        list33:'Bathroom Ceramic Wall Tiles with 7 feet height - Upto Rs.40 per Sqft',
        list333:'Sanitary ware &amp; CP Fittings - Upto Rs.30000 per 1000sqft of construction.',
        list3333:'CPVC Pipe - Astral or equivalent',
        list33333:'Bathroom doors - Waterproof flush doors',
        list4:'Door & Windows',
        list44:'Main Door - Flush Door With Veneer. Sal wood frame of 5 inch by 3 inch, worth Rs.13000 including fixtures',
        list444:'Internal Doors - Membrane doors / Flush Door with Laminates upto Rs.8000 including fixtures. Door Frames of Sal Wood 4inch by 2.5 inch',
        list4444:'Windows - Aluminium Windows with glass shutters and mesh shutters(3 track with 1 mesh)',
        list5:'Painting',
        list55:'Interior Painting - JK Putty + Tractor Emulsion or equivalent',
        list555:'Exterior Painting - Asian Primer + Ace Exterior Emulsion Paint or equivalent',
        list6:'Flooring',
        list66:'Living and Dining Flooring - Tiles of value upto Rs.50 per sqft',
        list666:'Rooms and Kitchen Flooring - Tiles upto Rs.50 per sqftExterior Painting - Asian Primer + Ace Exterior Emulsion Paint or equivalent',
        list6666:'Balcony and Open Areas Flooring - Anti-skid tiles of value upto Rs.40 per sqft',
        list66666:'Staircase Flooring - Sadarahalli Granite of value upto ₹ 70 per sqft',
        list666666:'Parking Tiles - Anti-skid tiles of value upto ₹40 per sqft',
        list7:'Electrical',
        list77:'Wires - Fireproof wires by Finolex',
        list777:'Switches &amp; Sockets - Anchor Roma',
        list8:'Miscellaneous',
        list88:'Overhead Tank - Sintex Double Layered 1000 ltrs',
        list888:'Underground Sump - 4000 litres',
        list8888:'Staircase Railing - MS Railing',
        list9:'Costomisation Costs',

    }]}


export const data1 = {
        Product1:[
            {
                package:'Budget Package - 1,950/sq.ft',
                list0:'Design & Drawing',
                list00:"Basic Elevation",
                list000:"Structural Design",
                list1:'Structure',
                list11:"Steel - Sunvik or Equivalent",
                list111:'Aggregates - 20mm&40mm',
                list1111:'Blocks - Standard Soild Concrete blocks. 6inch 4inch',
                list11111:'Cement - Dalmia , Coromandel or Zuari or equivalent Portland Pozzolona Cement',
                list111111:'RCC Design Mix - As Per the Structural designer recommentation',
                list1111111:'Celing height - 10 feet(Finished Floor level to Finished Floor Level)',
                list2:'Kitchen',
                list22:'Ceramic Wall Tiles, 2 feet above Kitchen slab - upto Rs.40per sqft',
                list222:'Main sink Faucet - upto Rs.1300',
                list2222:'Any Other Faucet & Accessories - ISI Marked',
                list22222:'Kitchen Sink - Stainless Steel Single Sink Worth Rs.3000',
                list3:'Bathroom',
                list33:'Bathroom Ceramic Wall Tiles with 7 feet height - Upto Rs.40 per Sqft',
                list333:'Sanitary ware &amp; CP Fittings - Upto Rs.30000 per 1000sqft of construction.',
                list3333:'CPVC Pipe - Astral or equivalent',
                list33333:'Bathroom doors - Waterproof flush doors',
                list4:'Door & Windows',
                list44:'Main Door - Flush Door With Veneer. Sal wood frame of 5 inch by 3 inch, worth Rs.13000 including fixtures',
                list444:'Internal Doors - Membrane doors / Flush Door with Laminates upto Rs.8000 including fixtures. Door Frames of Sal Wood 4inch by 2.5 inch',
                list4444:'Windows - Aluminium Windows with glass shutters and mesh shutters(3 track with 1 mesh)',
                list5:'Painting',
                list55:'Interior Painting - JK Putty + Tractor Emulsion or equivalent',
                list555:'Exterior Painting - Asian Primer + Ace Exterior Emulsion Paint or equivalent',
                list6:'Flooring',
                list66:'Living and Dining Flooring - Tiles of value upto Rs.50 per sqft',
                list666:'Rooms and Kitchen Flooring - Tiles upto Rs.50 per sqftExterior Painting - Asian Primer + Ace Exterior Emulsion Paint or equivalent',
                list6666:'Balcony and Open Areas Flooring - Anti-skid tiles of value upto Rs.40 per sqft',
                list66666:'Staircase Flooring - Sadarahalli Granite of value upto ₹ 70 per sqft',
                list666666:'Parking Tiles - Anti-skid tiles of value upto ₹40 per sqft',
                list7:'Electrical',
                list77:'Wires - Fireproof wires by Finolex',
                list777:'Switches &amp; Sockets - Anchor Roma',
                list8:'Miscellaneous',
                list88:'Overhead Tank - Sintex Double Layered 1000 ltrs',
                list888:'Underground Sump - 4000 litres',
                list8888:'Staircase Railing - MS Railing',
                list9:'Costomisation Costs',
        
            },
            {
                package:'Budget Package - 2,050/sq.ft',
                list0:'Design & Drawing',
                list00:"Basic Elevation",
                list000:"Structural Design",
                list1:'Structure',
                list11:"Steel - Sunvik or Equivalent",
                list111:'Aggregates - 20mm&40mm',
                list1111:'Blocks - Standard Soild Concrete blocks. 6inch 4inch',
                list11111:'Cement - Dalmia , Coromandel or Zuari or equivalent Portland Pozzolona Cement',
                list111111:'RCC Design Mix - As Per the Structural designer recommentation',
                list1111111:'Celing height - 10 feet(Finished Floor level to Finished Floor Level)',
                list2:'Kitchen',
                list22:'Ceramic Wall Tiles, 2 feet above Kitchen slab - upto Rs.40per sqft',
                list222:'Main sink Faucet - upto Rs.1300',
                list2222:'Any Other Faucet & Accessories - ISI Marked',
                list22222:'Kitchen Sink - Stainless Steel Single Sink Worth Rs.3000',
                list3:'Bathroom',
                list33:'Bathroom Ceramic Wall Tiles with 7 feet height - Upto Rs.40 per Sqft',
                list333:'Sanitary ware &amp; CP Fittings - Upto Rs.30000 per 1000sqft of construction.',
                list3333:'CPVC Pipe - Astral or equivalent',
                list33333:'Bathroom doors - Waterproof flush doors',
                list4:'Door & Windows',
                list44:'Main Door - Flush Door With Veneer. Sal wood frame of 5 inch by 3 inch, worth Rs.13000 including fixtures',
                list444:'Internal Doors - Membrane doors / Flush Door with Laminates upto Rs.8000 including fixtures. Door Frames of Sal Wood 4inch by 2.5 inch',
                list4444:'Windows - Aluminium Windows with glass shutters and mesh shutters(3 track with 1 mesh)',
                list5:'Painting',
                list55:'Interior Painting - JK Putty + Tractor Emulsion or equivalent',
                list555:'Exterior Painting - Asian Primer + Ace Exterior Emulsion Paint or equivalent',
                list6:'Flooring',
                list66:'Living and Dining Flooring - Tiles of value upto Rs.50 per sqft',
                list666:'Rooms and Kitchen Flooring - Tiles upto Rs.50 per sqftExterior Painting - Asian Primer + Ace Exterior Emulsion Paint or equivalent',
                list6666:'Balcony and Open Areas Flooring - Anti-skid tiles of value upto Rs.40 per sqft',
                list66666:'Staircase Flooring - Sadarahalli Granite of value upto ₹ 70 per sqft',
                list666666:'Parking Tiles - Anti-skid tiles of value upto ₹40 per sqft',
                list7:'Electrical',
                list77:'Wires - Fireproof wires by Finolex',
                list777:'Switches &amp; Sockets - Anchor Roma',
                list8:'Miscellaneous',
                list88:'Overhead Tank - Sintex Double Layered 1000 ltrs',
                list888:'Underground Sump - 4000 litres',
                list8888:'Staircase Railing - MS Railing',
                list9:'Costomisation Costs',
        
            },
            {
                package:'Budget Package - 2,150/sq.ft',
                list0:'Design & Drawing',
                list00:"Basic Elevation",
                list000:"Structural Design",
                list1:'Structure',
                list11:"Steel - Sunvik or Equivalent",
                list111:'Aggregates - 20mm&40mm',
                list1111:'Blocks - Standard Soild Concrete blocks. 6inch 4inch',
                list11111:'Cement - Dalmia , Coromandel or Zuari or equivalent Portland Pozzolona Cement',
                list111111:'RCC Design Mix - As Per the Structural designer recommentation',
                list1111111:'Celing height - 10 feet(Finished Floor level to Finished Floor Level)',
                list2:'Kitchen',
                list22:'Ceramic Wall Tiles, 2 feet above Kitchen slab - upto Rs.40per sqft',
                list222:'Main sink Faucet - upto Rs.1300',
                list2222:'Any Other Faucet & Accessories - ISI Marked',
                list22222:'Kitchen Sink - Stainless Steel Single Sink Worth Rs.3000',
                list3:'Bathroom',
                list33:'Bathroom Ceramic Wall Tiles with 7 feet height - Upto Rs.40 per Sqft',
                list333:'Sanitary ware &amp; CP Fittings - Upto Rs.30000 per 1000sqft of construction.',
                list3333:'CPVC Pipe - Astral or equivalent',
                list33333:'Bathroom doors - Waterproof flush doors',
                list4:'Door & Windows',
                list44:'Main Door - Flush Door With Veneer. Sal wood frame of 5 inch by 3 inch, worth Rs.13000 including fixtures',
                list444:'Internal Doors - Membrane doors / Flush Door with Laminates upto Rs.8000 including fixtures. Door Frames of Sal Wood 4inch by 2.5 inch',
                list4444:'Windows - Aluminium Windows with glass shutters and mesh shutters(3 track with 1 mesh)',
                list5:'Painting',
                list55:'Interior Painting - JK Putty + Tractor Emulsion or equivalent',
                list555:'Exterior Painting - Asian Primer + Ace Exterior Emulsion Paint or equivalent',
                list6:'Flooring',
                list66:'Living and Dining Flooring - Tiles of value upto Rs.50 per sqft',
                list666:'Rooms and Kitchen Flooring - Tiles upto Rs.50 per sqftExterior Painting - Asian Primer + Ace Exterior Emulsion Paint or equivalent',
                list6666:'Balcony and Open Areas Flooring - Anti-skid tiles of value upto Rs.40 per sqft',
                list66666:'Staircase Flooring - Sadarahalli Granite of value upto ₹ 70 per sqft',
                list666666:'Parking Tiles - Anti-skid tiles of value upto ₹40 per sqft',
                list7:'Electrical',
                list77:'Wires - Fireproof wires by Finolex',
                list777:'Switches &amp; Sockets - Anchor Roma',
                list8:'Miscellaneous',
                list88:'Overhead Tank - Sintex Double Layered 1000 ltrs',
                list888:'Underground Sump - 4000 litres',
                list8888:'Staircase Railing - MS Railing',
                list9:'Costomisation Costs',
        
            }
       ]
    };